# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('birthdayDate', models.DateTimeField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('mr', 'Monsieur'), ('mme', 'Madame'), ('mlle', 'Mademoiselle')], max_length=1)),
                ('level', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
    ]
